services:
  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twjobs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local