INSERT INTO `skills` 
    (id, name) 
VALUES
    (1, 'Java'),
    (2, 'C#'),
    (3, 'Python'),
    (4, 'JavaScript'),
    (5, 'TypeScript'),
    (6, 'Ruby'),
    (7, 'PHP'),
    (8, 'Swift'),
    (9, 'Objective-C'),
    (10, 'Kotlin'),
    (11, 'Scala'),
    (12, 'Go'),
    (13, 'Rust'),
    (14, 'Spring Boot'),
    (15, 'Spring MVC'),
    (16, 'Spring Data JPA'),
    (17, 'Spring Security'),
    (18, 'Spring Batch'),
    (19, 'ASP .NET'),
    (20, 'Django'),
    (21, 'Flask'),
    (22, 'React'),
    (23, 'Angular'),
    (24, 'Vue.js'),
    (25, 'Ember.js'),
    (26, 'Node.js'),
    (27, 'Express.js'),
    (28, 'Ruby on Rails'),
    (29, 'Laravel'),
    (30, 'Symfony'),
    (31, 'CakePHP'),
    (32, 'CodeIgniter'),
    (33, 'Zend Framework'),
    (34, 'MySQL'),
    (35, 'PostgreSQL'),
    (36, 'SQLite'),
    (37, 'MongoDB'),
    (38, 'Redis'),
    (39, 'Elasticsearch'),
    (40, 'SQL Server'),
    (41, 'Oracle'),
    (42, 'MariaDB'),
    (43, 'Firebase'),
    (44, 'AWS'),
    (45, 'Azure'),
    (46, 'Google Cloud'),
    (47, 'Heroku'),
    (48, 'Docker'),
    (49, 'Kubernetes'),
    (50, 'Jenkins'),
    (51, 'Travis CI'),
    (52, 'CircleCI'),
    (53, 'GitLab CI'),
    (54, 'GitHub Actions'),
    (55, 'SonarQube'),
    (56, 'Maven'),
    (57, 'Gradle'),
    (58, 'Ant'),
    (59, 'npm'),
    (60, 'Yarn'),
    (61, 'Bower'),
    (62, 'Gulp'),
    (63, 'Grunt'),
    (64, 'Webpack'),
    (65, 'Babel'),
    (66, 'Jest'),
    (67, 'JUnit'),
    (68, 'TestNG'),
    (69, 'Mockito'),
    (70, 'RestAssured'),
    (71, 'Postman'),
    (72, 'Swagger'),
    (73, 'OpenAPI'),
    (74, 'GraphQL'),
    (75, 'gRPC'),
    (76, 'SOAP'),
    (77, 'REST'),
    (78, 'WebSockets');
